SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF EXISTS drop table [roughsync].[Hcis2Rough_CONTROL_TABLE]
GO
CREATE TABLE [roughsync].[Hcis2Rough_CONTROL_TABLE](
	[IDNNO] [int] IDENTITY(1,1) NOT NULL,
	[TABLENAME] [varchar](512) NULL,
	[TABLEIDNNO] [bigint] NULL,
	[MODIFYDATETIME] [datetime] NULL,
	[LOCAL_TABLENAME] [varchar](255) NULL,
	[EXEC_SEQUENCE] [int] NULL,
	[IS_ACTIVE] [bit] NULL,
 CONSTRAINT [PK_Hcis2Rough_CONTROL_TABLE] PRIMARY KEY CLUSTERED 
(
	[IDNNO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UX_Hcis2Rough_CONTROL_TABLE_TABLENAME] UNIQUE NONCLUSTERED 
(
	[TABLENAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
