SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF EXISTS drop table [roughsync].[Hcis2Rough_DATASYNC_MASTER]
GO
CREATE TABLE [roughsync].[Hcis2Rough_DATASYNC_MASTER](
	[TABLE_NAME] [varchar](128) NOT NULL,
	[P2L_LOCAL_FILL] [varchar](128) NULL,
	[P2L_REMOTE_TABLE] [varchar](128) NULL,
	[ACTIVE] [bit] NOT NULL,
	[EXEC_SEQUENCE] [int] NOT NULL,
	[CONTROL_TABLE_NAME] [varchar](120) NULL,
	[SYNC_TYPE] [varchar](4) NULL,
 CONSTRAINT [PK_Hcis2Rough_DATASYNC_MASTER] PRIMARY KEY CLUSTERED 
(
	[TABLE_NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
